package software;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alaa
 */
public class AdminMain extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public AdminMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        HRS = new javax.swing.JMenu();
        searchCust = new javax.swing.JMenuItem();
        SA = new javax.swing.JMenuItem();
        SC = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AF = new javax.swing.JMenuItem();
        SF = new javax.swing.JMenuItem();
        AB = new javax.swing.JMenu();
        TR1 = new javax.swing.JMenuItem();
        SB = new javax.swing.JMenuItem();
        TR = new javax.swing.JMenu();
        BT = new javax.swing.JMenuItem();
        FT = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1400, 1050));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 1050));

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1103, 1103, 1103)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(583, 583, 583)
                .addComponent(cancel)
                .addContainerGap(436, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        HRS.setText("HRS");
        HRS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRSActionPerformed(evt);
            }
        });

        searchCust.setText("Add Admin");
        searchCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustActionPerformed(evt);
            }
        });
        HRS.add(searchCust);

        SA.setText("Search Admin");
        SA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAActionPerformed(evt);
            }
        });
        HRS.add(SA);

        SC.setText("Search Customer");
        SC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCActionPerformed(evt);
            }
        });
        HRS.add(SC);

        jMenuBar1.add(HRS);

        jMenu2.setText("Flight");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        AF.setText("Add Flight");
        AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFActionPerformed(evt);
            }
        });
        jMenu2.add(AF);

        SF.setText("Search Flight");
        SF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SFActionPerformed(evt);
            }
        });
        jMenu2.add(SF);

        jMenuBar1.add(jMenu2);

        AB.setText("Bus");
        AB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        TR1.setText("Add Bus");
        TR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TR1ActionPerformed(evt);
            }
        });
        AB.add(TR1);

        SB.setText("Search Bus");
        SB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SBActionPerformed(evt);
            }
        });
        AB.add(SB);

        jMenuBar1.add(AB);

        TR.setText("Tickets Report");
        TR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        BT.setText("Bus tickets");
        BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActionPerformed(evt);
            }
        });
        TR.add(BT);

        FT.setText("Flight tickets");
        FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTActionPerformed(evt);
            }
        });
        TR.add(FT);

        jMenuBar1.add(TR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustActionPerformed
        // TODO add your handling code here:
    addAdmin am = new addAdmin();
        jDesktopPane1.add(am);
        am.setVisible(true);
                           
    }//GEN-LAST:event_searchCustActionPerformed

    private void AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFActionPerformed
    addFlight af = new addFlight();
        jDesktopPane1.add(af);
        af.setVisible(true);
    }//GEN-LAST:event_AFActionPerformed

    private void HRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HRSActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        this.hide();
        m.setVisible(true);
      
    }//GEN-LAST:event_cancelActionPerformed

    private void TR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TR1ActionPerformed
        addBus ab = new addBus();
        jDesktopPane1.add(ab);
        ab.setVisible(true);
    }//GEN-LAST:event_TR1ActionPerformed

    private void SAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAActionPerformed
        searchAdmin sa = new searchAdmin();
        jDesktopPane1.add(sa);
        sa.setVisible(true);
    }//GEN-LAST:event_SAActionPerformed

    private void SCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCActionPerformed
        // TODO add your handling code here:
        searchCustomer sc = new searchCustomer();
        jDesktopPane1.add(sc);
        sc.setVisible(true);
    }//GEN-LAST:event_SCActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void SFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SFActionPerformed
        // TODO add your handling code here:
         searchFlight sf = new searchFlight();
        jDesktopPane1.add(sf);
        sf.setVisible(true);
    }//GEN-LAST:event_SFActionPerformed

    private void BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActionPerformed
        // TODO add your handling code here:
         ticketReportBus trb = new ticketReportBus();
        jDesktopPane1.add(trb);
        trb.setVisible(true);
    }//GEN-LAST:event_BTActionPerformed

    private void FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTActionPerformed
        // TODO add your handling code here:
        ticketReportAir tra = new ticketReportAir();
        jDesktopPane1.add(tra);
        tra.setVisible(true);
    }//GEN-LAST:event_FTActionPerformed

    private void SBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SBActionPerformed
        // TODO add your handling code here:
          searchBus sb = new searchBus();
        jDesktopPane1.add(sb);
        sb.setVisible(true);
    }//GEN-LAST:event_SBActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AB;
    private javax.swing.JMenuItem AF;
    private javax.swing.JMenuItem BT;
    private javax.swing.JMenuItem FT;
    private javax.swing.JMenu HRS;
    private javax.swing.JMenuItem SA;
    private javax.swing.JMenuItem SB;
    private javax.swing.JMenuItem SC;
    private javax.swing.JMenuItem SF;
    private javax.swing.JMenu TR;
    private javax.swing.JMenuItem TR1;
    private javax.swing.JButton cancel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem searchCust;
    // End of variables declaration//GEN-END:variables
}
